### PR TITLE
Updated project to Ember 2.4 & Added small new feature

### PR DESCRIPTION
**Pull request by jakemoves**
Hey, I found this component quite useful, but I wanted to add a small feature (the ability to pass in a label for the Save button).

I forked your repo, added the feature, went to add a test, and found that I couldn't get the tests to run at all. I spent a few hours yesterday trying and got nowhere. Might be an ember-cli version issue, might be something else entirely. Testem just stalled out 'waiting for runners' no matter what I did.

Anyways, I ended up generating a new addon (using ember-cli@2.4.3) and bringing your code and tests into that new project. I changed as little as possible along the way (a few things to prevent jshint from yelling).

Of course, now this is a substantial PR that (being based on a project generated using a more recent version of Ember) may not fit your needs...on the other hand, maybe this is useful for other people looking to contribute.

I apologize if this seems presumptive. I'll understand if you would rather keep the project scaffolding as it was. 

In that case, I could make a new PR with just the changes to ember-inline-edit.js, ember-inline-edit.hbs, and ember-inline-edit-test.js (the small new feature) and ignoring all the other file changes.

Or whatever you think is best :)

### CODE REVIEW

**Comment by swastik** [comment]
This is a wonderful PR! :smile:

I ran the tests locally and everything seems fine. I'll merge this.

One thing though: can you please commit the previous README back? It seems to have gone back to the default ember-cli README in this commit.

Thank you so much! :smiley:

**Comment by jakemoves** [comment]
Ah happy to hear that. I'll restore the readme, I think I briefly went diff-blind.

**Comment by jakemoves** [comment]
Ok, I've updated the README, so this should be good to go.

**Comment by swastik** [comment]
Thank you! I've merged it; I'll publish a new release tomorrow. :smiley:

**Comment by mwadden** [comment]
Hi @swastik, any chance this feature will be releasing soon? Many thanks!

**Comment by swastik** [comment]
@mwadden — Sorry, I totally forgot! 😃 

I've published it now. The version is `0.1.5`.

**Pull request merged**
