### PR TITLE
Adds custom classnames for several elements in the component

### PR DESCRIPTION
**Pull request by armiiller**
Adds editor, buttonContainer, saveButton, cancelButton, and editButton the ability for custom classnames

### CODE REVIEW

**Comment by swastik** [comment]
@armiiller Thanks! 😃  This looks good. It seems like the tests fail on the newest ember release due to some incompatible plugin; I'll look into that and merge this.

**Comment by armiiller** [comment]
@swastik - Thanks for the quick look into this and the test. 👍

**Comment by swastik** [comment]
@armiiller Thanks once again, this is merged. It turned out we needed to update ember to get past the failures.

**Comment by armiiller** [comment]
Fantastic! Thanks for looking at that and getting it merged in :)

**Pull request merged**
